// 8_DotNet_Kanban/frontend/src/app/chat/chat-sidebar.component.ts
import { Component, ElementRef, ViewChild, inject, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import { BoardData } from '../models/board.models';
import { BoardService } from '../board/board.service';

interface Message { role: 'user' | 'assistant'; content: string; }

@Component({
  selector: 'app-chat-sidebar',
  standalone: true,
  imports: [FormsModule],
  template: `
    <aside class="w-80 flex-shrink-0 flex flex-col bg-white border-l border-gray-100 shadow-xl shadow-indigo-900/5">

      <!-- Header -->
      <div class="px-5 py-4 bg-gradient-to-r from-indigo-700 to-purple-700 flex items-center gap-3">
        <div class="flex items-center justify-center w-8 h-8 rounded-lg bg-white/20">
          <svg class="w-4 h-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round"
              d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-4 4v-4z"/>
          </svg>
        </div>
        <div>
          <h2 class="text-sm font-bold text-white">AI Assistant</h2>
          <p class="text-xs text-white/50">Powered by GPT-OSS 120B</p>
        </div>
      </div>

      <!-- Messages -->
      <div #scrollContainer class="flex-1 overflow-y-auto px-4 py-4 space-y-3">

        @if (messages().length === 0) {
          <div class="flex flex-col items-center justify-center h-full gap-3 text-center py-8">
            <div class="w-12 h-12 rounded-2xl bg-indigo-50 flex items-center justify-center">
              <svg class="w-6 h-6 text-indigo-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5">
                <path stroke-linecap="round" stroke-linejoin="round"
                  d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z"/>
              </svg>
            </div>
            <div>
              <p class="text-sm font-medium text-gray-700">Ask me anything</p>
              <p class="text-xs text-gray-400 mt-1">I can create, move, rename,<br>or delete cards and columns.</p>
            </div>
            <!-- Quick suggestions -->
            <div class="w-full space-y-1.5 mt-2">
              @for (s of suggestions; track s) {
                <button (click)="sendSuggestion(s)"
                        class="w-full text-left text-xs text-indigo-600 bg-indigo-50 hover:bg-indigo-100
                               rounded-lg px-3 py-2 transition-colors border border-indigo-100">
                  {{ s }}
                </button>
              }
            </div>
          </div>
        }

        @for (msg of messages(); track $index) {
          <div [class]="msg.role === 'user' ? 'flex justify-end' : 'flex justify-start'">
            @if (msg.role === 'assistant') {
              <div class="w-6 h-6 rounded-full bg-gradient-to-br from-indigo-500 to-purple-600
                          flex items-center justify-center flex-shrink-0 mr-2 mt-0.5">
                <svg class="w-3 h-3 text-white" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M10 2a8 8 0 100 16A8 8 0 0010 2z"/>
                </svg>
              </div>
            }
            <div class="max-w-[80%] rounded-2xl px-3.5 py-2.5 text-sm leading-relaxed"
                 [class.bg-indigo-600]="msg.role === 'user'"
                 [class.text-white]="msg.role === 'user'"
                 [class.rounded-br-sm]="msg.role === 'user'"
                 [class.bg-gray-100]="msg.role === 'assistant'"
                 [class.text-gray-800]="msg.role === 'assistant'"
                 [class.rounded-bl-sm]="msg.role === 'assistant'">
              {{ msg.content }}
            </div>
          </div>
        }

        @if (loading()) {
          <div class="flex justify-start items-center gap-2">
            <div class="w-6 h-6 rounded-full bg-gradient-to-br from-indigo-500 to-purple-600
                        flex items-center justify-center flex-shrink-0">
              <svg class="w-3 h-3 text-white" fill="currentColor" viewBox="0 0 20 20">
                <path d="M10 2a8 8 0 100 16A8 8 0 0010 2z"/>
              </svg>
            </div>
            <div class="bg-gray-100 rounded-2xl rounded-bl-sm px-4 py-2.5 flex gap-1 items-center">
              <span class="w-1.5 h-1.5 bg-gray-400 rounded-full animate-bounce [animation-delay:-0.3s]"></span>
              <span class="w-1.5 h-1.5 bg-gray-400 rounded-full animate-bounce [animation-delay:-0.15s]"></span>
              <span class="w-1.5 h-1.5 bg-gray-400 rounded-full animate-bounce"></span>
            </div>
          </div>
        }
      </div>

      <!-- Input -->
      <div class="px-4 py-4 border-t border-gray-100 bg-gray-50/50">
        <div class="flex items-end gap-2 bg-white rounded-2xl border border-gray-200
                    focus-within:border-indigo-400 focus-within:ring-2 focus-within:ring-indigo-500/20
                    px-3 py-2 shadow-sm transition-all">
          <textarea [(ngModel)]="input"
                    (keydown.enter)="onEnter($event)"
                    [disabled]="loading()"
                    rows="1"
                    class="flex-1 text-sm text-gray-800 resize-none outline-none bg-transparent
                           placeholder-gray-400 max-h-24 leading-relaxed"
                    placeholder="Ask the AI…"></textarea>
          <button (click)="send()"
                  [disabled]="loading() || !input.trim()"
                  class="flex-shrink-0 w-8 h-8 rounded-xl flex items-center justify-center
                         bg-gradient-to-br from-indigo-500 to-purple-600 text-white
                         hover:from-indigo-400 hover:to-purple-500
                         disabled:opacity-40 disabled:cursor-not-allowed
                         shadow-sm shadow-indigo-500/30 transition-all active:scale-95">
            <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.5">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 12L3.269 3.126A59.768 59.768 0 0121.485 12 59.77 59.77 0 013.27 20.876L5.999 12zm0 0h7.5"/>
            </svg>
          </button>
        </div>
      </div>

    </aside>
  `
})
export class ChatSidebarComponent {
  @ViewChild('scrollContainer') private scrollContainer!: ElementRef<HTMLDivElement>;

  private http = inject(HttpClient);
  private boardService = inject(BoardService);

  messages = signal<Message[]>([]);
  input    = '';
  loading  = signal(false);

  readonly suggestions = [
    '✨ Add a card called "Fix login bug" to To Do',
    '🚀 Move all Done cards to In Progress',
    '📋 Add a new column called "Review"',
  ];

  sendSuggestion(text: string): void {
    this.input = text;
    this.send();
  }

  onEnter(event: Event): void {
    const e = event as KeyboardEvent;
    if (!e.shiftKey) {
      e.preventDefault();
      this.send();
    }
  }

  async send(): Promise<void> {
    const msg = this.input.trim();
    if (!msg || this.loading()) return;

    this.input = '';
    this.messages.update(m => [...m, { role: 'user', content: msg }]);
    this.loading.set(true);
    this.scrollToBottom();

    try {
      const res = await firstValueFrom(
        this.http.post<{ message: string; board_update: BoardData | null }>('/api/ai/chat', { message: msg })
      );
      this.messages.update(m => [...m, { role: 'assistant', content: res.message }]);
      if (res.board_update) this.boardService.applyAiBoardUpdate(res.board_update);
    } catch (err: any) {
      const detail = err?.error?.detail ?? 'Something went wrong. Please try again.';
      this.messages.update(m => [...m, { role: 'assistant', content: detail }]);
    } finally {
      this.loading.set(false);
      setTimeout(() => this.scrollToBottom(), 50);
    }
  }

  private scrollToBottom(): void {
    setTimeout(() => {
      if (this.scrollContainer) {
        this.scrollContainer.nativeElement.scrollTop = this.scrollContainer.nativeElement.scrollHeight;
      }
    }, 0);
  }
}

// 7_FullStack/frontend/src/components/ChatSidebar.tsx
"use client";

import React, { useState, useRef, useEffect, useCallback } from "react";
import type { BoardData } from "@/lib/kanban";

type ChatMessage = {
  role: "user" | "assistant";
  content: string;
};

type ChatSidebarProps = {
  board: BoardData | null;
  onBoardUpdated: () => void;
};

const boardToApiFormat = (board: BoardData) => {
  const columns = board.columns.map((col, colIdx) => ({
    id: col.id,
    title: col.title,
    position: colIdx,
    cards: col.cardIds.map((cardId, cardIdx) => ({
      id: cardId,
      title: board.cards[cardId]?.title ?? "",
      details: board.cards[cardId]?.details ?? "",
      position: cardIdx,
    })),
  }));
  return { columns };
};

export const ChatSidebar: React.FC<ChatSidebarProps> = ({
  board,
  onBoardUpdated,
}) => {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView?.({ behavior: "smooth" });
  }, [messages, isLoading]);

  const sendMessage = useCallback(async () => {
    if (!input.trim() || isLoading) return;

    const userMessage: ChatMessage = { role: "user", content: input };
    setMessages((prev) => [...prev, userMessage]);
    setInput("");
    setIsLoading(true);
    setError(null);

    try {
      const boardState = board ? boardToApiFormat(board) : null;
      const res = await fetch("/api/ai/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message: input, board: boardState }),
      });

      if (!res.ok) {
        const errData = await res.json().catch(() => ({}));
        throw new Error(errData.detail || `Server error: ${res.status}`);
      }

      const data = await res.json();
      const assistantMessage: ChatMessage = {
        role: "assistant",
        content: data.message,
      };
      setMessages((prev) => [...prev, assistantMessage]);

      if (data.board_updated) {
        onBoardUpdated();
      }
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Unknown error";
      setError(msg);
      setMessages((prev) => [
        ...prev,
        { role: "assistant", content: `Error: ${msg}` },
      ]);
    } finally {
      setIsLoading(false);
    }
  }, [input, board, isLoading, onBoardUpdated]);

  return (
    <aside className="flex min-h-[520px] flex-col rounded-2xl border border-[var(--navy-dark)]/20 bg-[var(--navy-dark)] p-4 shadow-lg">
      <div className="mb-4 flex items-center gap-3">
        <div className="flex h-8 w-8 items-center justify-center rounded-full bg-[var(--accent-yellow)]">
          <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-[var(--navy-dark)]" viewBox="0 0 24 24" fill="currentColor">
            <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm-1-4h2v2h-2zm1-2c1.1 0 2-.9 2-2V8c0-1.1-.9-2-2-2s-2 .9-2 2v4c0 1.1.9 2 2 2z"/>
          </svg>
        </div>
        <h2 className="text-xs font-semibold uppercase tracking-[0.2em] text-white/70">
          AI Assistant
        </h2>
      </div>

      {messages.length === 0 && (
        <div className="flex flex-1 flex-col items-center justify-center py-8 text-center">
          <p className="mb-2 text-sm text-white/60">
            Ask me to create, move, or edit cards.
          </p>
          <p className="text-xs text-white/40">
            Try: &quot;Create a card called Setup CI in To Do&quot;
          </p>
        </div>
      )}

      <div className="flex-1 overflow-y-auto">
        {messages.map((msg, i) => (
          <div
            key={i}
            className={`mb-3 flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}
          >
            <div
              className={`max-w-[90%] rounded-lg px-3 py-2 text-sm leading-relaxed ${
                msg.role === "user"
                  ? "bg-[var(--primary-blue)] text-white"
                  : "bg-white/10 text-white/90 backdrop-blur"
              }`}
            >
              {msg.content}
            </div>
          </div>
        ))}

        {isLoading && (
          <div className="mb-3 flex justify-start">
            <div className="rounded-lg bg-white/10 px-3 py-2 text-sm text-white/40 backdrop-blur">
              Thinking...
            </div>
          </div>
        )}

        {error && (
          <div className="mb-3 rounded-lg bg-red-500/20 px-3 py-2 text-xs text-red-300 border border-red-500/30">
            {error}
          </div>
        )}

        <div ref={bottomRef} />
      </div>

      <div className="mt-4 border-t border-white/10 pt-3">
        <form
          onSubmit={(e) => {
            e.preventDefault();
            sendMessage();
          }}
          className="flex gap-2"
        >
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Ask AI..."
            className="flex-1 rounded-lg border border-white/20 bg-white/10 px-3 py-2 text-sm text-white placeholder-white/40 focus:border-[var(--accent-yellow)] focus:outline-none focus:ring-1 focus:ring-[var(--accent-yellow)]"
            disabled={isLoading}
          />
          <button
            type="submit"
            disabled={isLoading || !input.trim()}
            className="rounded-lg bg-[var(--accent-yellow)] px-4 py-2 text-sm font-semibold text-[var(--navy-dark)] disabled:opacity-50 hover:bg-[var(--accent-yellow)]/90"
          >
            Send
          </button>
        </form>
      </div>
    </aside>
  );
};
